# Generated by Django 5.2.1 on 2025-05-24 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('venueName', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('venueType', models.CharField(choices=[('GYM', 'Gym'), ('POOL', 'Swimming Pool'), ('STUDIO', 'Fitness Studio'), ('FIELD', 'Sports Field'), ('OTHER', 'Other')], max_length=10)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('facilities', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Venue',
                'verbose_name_plural': 'Partner Venues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waitlist User',
                'verbose_name_plural': 'Waitlist Users',
            },
        ),
    ]
